/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;
import dto.AttivitaJoinUtenteDto;
import dto.UtenteDto;
import entita.Attivita;
import entita.Utente;
import gui.modelloGrafico.ModelloAttivitaDto;
import java.util.List;
import java.util.Optional;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import service.AttivitaService;
import service.UtenteService;

/**
 *
 * @author win
 */
public class InserisciAttivita extends javax.swing.JFrame {
    private AttivitaService attivitaService;
    private UtenteService  utenteService;

    /**
     * Creates new form inserisciAttivita
     */
    public InserisciAttivita() {
          attivitaService=new AttivitaService();
           utenteService=new UtenteService();
 JOptionPane.showMessageDialog(rootPane, attivitaService.getAttivitaUtente().toString());
        initComponents();
      
          UtenteService utenteService = new UtenteService();
      List<UtenteDto> utentiDto =utenteService.getUtenti();
      jComboBox1.removeAllItems();
      rimuoviRigheEColonneTabella();
      
     // JOptionPane.showMessageDialog(getContentPane(), attivitaService.trovaAttivita("calcio"));
    //  this.attivitaService.testQuery();
  //  attivitaService.getAttivitaUtente().forEach(a->{System.out.print(a+" ");});
   //  System.out.println();
    
     
      for(UtenteDto utenteDto:utentiDto) {
          this.jComboBox1.addItem(utenteDto.getEmail());
      }
      
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etichetta1 = new javax.swing.JLabel();
        testoAttivita = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        etichettaUtente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabella = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etichetta1.setText("inserisci l'attvità");

        jButton1.setText("INSERISCI ATTIVITA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        etichettaUtente.setText("inserisci l'email ell'utente");

        tabella.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabella);

        jButton2.setText("VISUALIZZA ATTIVITA' UTENTI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etichetta1)
                            .addComponent(etichettaUtente)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(testoAttivita, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etichetta1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(testoAttivita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etichettaUtente))
                        .addGap(48, 48, 48)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nomeAttivita = this.testoAttivita.getText();
       
       String controllo = controllaParametro(nomeAttivita);
       if(controllo.equals("OK")) {
         Attivita attivita = new Attivita(nomeAttivita);
         String utenteSelezionato = (String)jComboBox1.getSelectedItem();
         Optional<Utente> utenteOpt = utenteService.trovaEmailUtente(utenteSelezionato);
         if(utenteOpt.isPresent()) {
            attivita.setUtente(utenteOpt.get());
         }
         attivitaService.aggiungiAttivita(attivita);
         JOptionPane.showMessageDialog(getContentPane(), "attività inserita correttamente");
    System.out.println(attivitaService.getAttivitaUtente());
      
       
         
       }
       else {
           JOptionPane.showMessageDialog(getContentPane(),"Errore "+ controllo);
       
       }
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
      
      
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ModelloAttivitaDto modello = new ModelloAttivitaDto();
        modello.setLista(attivitaService.getAttivitaUtente());
        this.tabella.setModel(modello);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserisciAttivita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserisciAttivita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserisciAttivita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserisciAttivita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InserisciAttivita ia=new InserisciAttivita();
               ia.setVisible(true);
               ia.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etichetta1;
    private javax.swing.JLabel etichettaUtente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabella;
    private javax.swing.JTextField testoAttivita;
    // End of variables declaration//GEN-END:variables

    private String controllaParametro(String nomeAttivita) {
        String risultato="OK";
        if(nomeAttivita==null || nomeAttivita.isEmpty()) {
            risultato="Errore nome attivita vuoto";
        }
       if(attivitaService.esisteAttivita(nomeAttivita)) {
            risultato="errore nome attività duplicato ";
        }
      
             
        
        return risultato;
     
    }
 private void rimuoviRigheEColonneTabella() {
          DefaultTableModel model =(DefaultTableModel) tabella.getModel();
            for(int i = model.getRowCount()-1; i>=0; i--)
           model.removeRow(i);
       TableColumnModel tableModel = tabella.getColumnModel();
     for(int i = tableModel.getColumnCount()-1; i>=0; i--) {
         TableColumn tcol = tableModel.getColumn(i);
         tabella.removeColumn(tcol);
    }
 }
}
